Update create discussion workflow 1
route06/actions pull request #53
Opened 2024-07-08 01:01 UTC by TomckySan

[この辺](https://github.com/route06/actions/pull/52#pullrequestreview-2159628912) の修正を入れています。

- description_template_path の中身が空の時はデフォルトコンテンツを入れる
- 週次だけでなく、日次や月次のdiscussion作成でも使えるように、discussion作成だけにworkflowの処理を絞り、日付つきタイトルは呼び出し元で設定する
    - Starter Workflowとしてパターンを作成する想定

2024-07-08 04:27 UTC, masutaka requested changes
> description_template_path の中身が空の時はデフォルトコンテンツを入れる

検討項目が多そうなので、本 PR では↑の変更だけに絞ったほうが良いと思いました。

2024-07-08 04:27 UTC, masutaka commented on .github/workflows/create_discussion.yml
> +#       target_date: ${{ steps.get_date.outputs.target_date }}
このコードがテンプレートとして作用し各所にコピーされてしまうので、これ自体を reusable workflow にしたほうが良いと思います。

最終的には `@usage` が少なくとも 2 種類になると思いますし、別 PR にしたほうが良いと思いました。

## (1) ユーザーがタイトルを設定する

```yaml
jobs:
  create_discussion:
    uses: route06/actions/.github/workflows/create_discussion.yml@v2
    with:
      title: ミーティングのタイトル
      discussion_category_slug: general
      description_template_path: _templates/weekly_meeting_discussion/test.md
```

## (2) ユーザーが設定したタイトルに 'yyyy/mm/dd ' を付与する

```yaml
jobs:
  calculate_next_date:
    uses: route06/actions/.github/workflows/calculate_next_date.yml@v2
    with:
      target_day: monday
    outputs:
      target_date: ...

  create_discussion:
    needs: [calculate_next_date]
    uses: route06/actions/.github/workflows/create_discussion.yml@v2
    with:
      title: "${{ needs.calculate_next_date.outputs.target_date }} ミーティングのタイトル"
      discussion_category_slug: general
      description_template_path: _templates/weekly_meeting_discussion/test.md
```

P.S.
.github/workflows/calculate_next_date.yml に機能を追加して賢くすれば、with の指定で月次/年次などにも対応できると思います。

2024-07-08 04:34 UTC, masutaka commented on .github/workflows/create_discussion.yml
> +#       target_date: ${{ steps.get_date.outputs.target_date }}
P.P.S.
calculate_next_date.yml の実装イメージは、例えば https://github.com/lee-dohm/calculate-dates-and-times です。

2024-07-08 12:16 UTC, TomckySan commented on .github/workflows/create_discussion.yml
> +            }
提案ありがとうございます！
いずれも違和感ないご指摘なので、そのままコミットさせてください！

2024-07-08 12:18 UTC, TomckySan commented
@masutaka 
https://github.com/route06/actions/pull/53#discussion_r1667943164
上記提案を取り込みました。また2点目ご指摘の部分は別のPRで解消するとして、ほか違和感なければ、こちらはマージしたいと考えていますが、いかがでしょうか？

2024-07-09 02:32 UTC, masutaka commented
@TomckySan この PR のマージ先を、main ブランチから feature ブランチにするのはどうでしょうか？

> また2点目ご指摘の部分は別のPRで解消するとして、

↑ これらは feature ブランチへの PR にします。feature ブランチから main ブランチへの PR は Draft で作っておき、全部解消したら In Review にします。

こんな理由からです。

* main ブランチは出来るだけ、すぐリリース出来る状態を保っておきたい
    * そういう意味では https://github.com/route06/actions/pull/52 のマージ先を feature ブランチにすれば良かったかも
* main ブランチにマージしたものは、出来るだけ破壊的な変更をしたくない

📝 今回の feature ブランチの作り方（私やれます）

```
$ git checkout f283caff7cc2cee53c60b2cf2ea1ea3a47c02337 # PR #53 の分岐元
$ git checkout -b feature-create-discussion             # feature ブランチ
$ git push origin feature-create-discussion             # このブランチで Draft PR 作る
```

2024-07-09 02:36 UTC, TomckySan commented
@masutaka 
その運用で問題ないです！branchはこちらで切れるので、対応しますね 🚀

2024-07-09 02:57 UTC, MH4GF commented
遅れました、みますね！(マージ直前だと思うので軽く見ます！)

2024-07-09 03:01 UTC, MH4GF approved these changes
masutakaさんの指摘以外は問題ないように見えました！
もうちょっとですね...!ご対応ありがとうございます！！

2024-07-09 03:11 UTC, masutaka commented
📝 マージ先が main から feature ブランチに変更されたら Approve する

2024-07-09 08:02 UTC, TomckySan commented
@masutaka 
https://github.com/route06/actions/tree/feature ブランチを作成し、PRのbaseブランチをそちらに変えました。
ご確認よろしくお願いします！

2024-07-09 08:05 UTC, masutaka approved these changes
LGTM!

2024-07-09 08:11 UTC, merged