スケジュールされた次の日付を取得するワークフローを作成
route06/actions pull request #59
Opened 2024-07-17 02:52 UTC by TomckySan

タイトルのとおりです。
[このあたりのやり残し](https://github.com/route06/actions/pull/53#discussion_r1667972901) になります！

できること。
日次, 週次, 月次, 年次での日付をyyyy/mm/ddで取得できる。

日付のフォーマットを変えられる、というのは今回のスコープから外しました。

2024-07-17 02:52 UTC, TomckySan commented
動作確認のjob
https://github.com/TomckySan/sandbox/actions/runs/9967358121/job/27540916616

2024-07-17 08:41 UTC, masutaka requested changes
README.md にリンクも追加お願いします🙏

2024-07-17 08:41 UTC, masutaka commented on .github/workflows/get_next_scheduled_date.yml
> +                if [ "$today" \< "${{ inputs.target_date }}" ]; then
Bash で文字列に `<` 演算子使えたのですね😳

🔗 https://www.gnu.org/software/bash/manual/html_node/Bash-Conditional-Expressions.html

```
string1 < string2
    True if string1 sorts before string2 lexicographically.
```

```bash
#!/bin/bash

# $(gdate +%m-%d)
# -> 07-17

if [ '07-19' \< '07-20' ]; then
  echo true
else
  echo false
fi

if [ '07-19' \< '07-18' ]; then
  echo true
else
  echo false
fi
```

↓

```
true
false
```

2024-07-17 08:41 UTC, masutaka commented on .github/workflows/get_next_scheduled_date.yml
> +        run: |
a5ae7d4e2435606e252a363ad9f75fc7544628b2 で修正されたので Resolve にする。reviewdog 側でやって欲しい...。

https://www.shellcheck.net/wiki/SC2170

2024-07-17 08:41 UTC, masutaka commented on .github/workflows/get_next_scheduled_date.yml
> +        run: |
a5ae7d4e2435606e252a363ad9f75fc7544628b2 で修正されたので Resolve にする。reviewdog 側でやって欲しい...。

https://www.shellcheck.net/wiki/SC2170

2024-07-17 08:41 UTC, masutaka commented on .github/workflows/get_next_scheduled_date.yml
> +#     uses: route06/actions/.github/workflows/get_next_scheduled_date.yml@test-calculate-next-date
must: 現在は v2 タグを指定します。

```suggestion
#     uses: route06/actions/.github/workflows/get_next_scheduled_date.yml@v2
```

2024-07-17 08:41 UTC, masutaka commented on .github/workflows/get_next_scheduled_date.yml
> +            fi
case 文使うとスッキリすると思いますよ。

```bash
case "${{ inputs.target_schedule }}" in
  daily)
    # ...
    ;;
  weekly)
    # ...
    ;;
  monthly)
    # ...
    ;;
  yearly)
    # ...
    ;;
  *)
    echo "Invalid TARGET_SCHEDULE value"
    exit 1
    ;;
esac
```

2024-07-17 08:41 UTC, masutaka commented on .github/workflows/get_next_scheduled_date.yml
> +                fi
@TomckySan target_date=30 且つ、今日が 2/20 の時はどんな振る舞いになります？

Bash での日付の計算はいろいろ難しいので、Ruby 等で実装したほうが間違いがないかも...？💦

2024-07-17 08:41 UTC, masutaka commented on .github/workflows/get_next_scheduled_date.yml
> +      target_schedule:
他との兼ね合いもありますが、このケースだと "interval" は一般的だと思います。

2024-07-19 05:17 UTC, TomckySan commented on .github/workflows/get_next_scheduled_date.yml
> +                if [ "$today" \< "${{ inputs.target_date }}" ]; then
らしいです！

2024-07-19 05:17 UTC, TomckySan commented on .github/workflows/get_next_scheduled_date.yml
> +#     uses: route06/actions/.github/workflows/get_next_scheduled_date.yml@test-calculate-next-date
🙏🏻 🙏🏻 🙏🏻

2024-07-19 05:18 UTC, TomckySan commented on .github/workflows/get_next_scheduled_date.yml
> +      target_schedule:
`target_schedule` → `interval` ってことですよね？

2024-07-19 06:08 UTC, TomckySan commented on .github/workflows/get_next_scheduled_date.yml
> +                fi
`date: invalid date ‘2024-02-30’` となって、落ちますね
どうするといいかな 💭 

> Bash での日付の計算はいろいろ難しいので、Ruby 等で実装したほうが間違いがないかも...？💦

それは、そうだな。。の気持ちす。Rubyで組み直すか（Rubyのスクリプト走らせる方法よくわかってない）

2024-07-19 06:13 UTC, masutaka commented on .github/workflows/get_next_scheduled_date.yml
> +      target_schedule:
です！ が、ここだけ変えて他のコードと整合性が取れるかは分からないです。

2024-07-19 06:14 UTC, masutaka commented on .github/workflows/get_next_scheduled_date.yml
> +                fi
@TomckySan 今回は一旦 daily と weekly のみサポートにするのはどうでしょう？

2024-07-19 06:16 UTC, TomckySan commented on .github/workflows/get_next_scheduled_date.yml
> +                fi
@masutaka 

> 今回は一旦 daily と weekly のみサポートにするのはどうでしょう？

あ、その方針でリリースまで進められるなら、ありがたいです！
それであれば、スクリプトもBashのままで行きたい気持ちがあるます 🙏🏻

2024-07-19 06:17 UTC, TomckySan commented on .github/workflows/get_next_scheduled_date.yml
> +            fi
たしかに 💡 

> 今回は一旦 daily と weekly のみサポートにするのはどうでしょう？

この対応と合わせて、書き換えようと思います！ 🙌🏻

2024-07-19 06:18 UTC, masutaka commented on .github/workflows/get_next_scheduled_date.yml
> +                fi
ではそれで！
バグがあると分かっているものや、今後破壊的な変更があるものをリリースしなければよいと思います。

2024-07-19 12:34 UTC, TomckySan commented
READMEにリンク追加しました！
d895faf069376fd48652615d48cb730389c589a2

2024-07-19 12:40 UTC, TomckySan commented on .github/workflows/get_next_scheduled_date.yml
> +                fi
対応しました 🚀 
7c54d96e4bc8a8cda8d45caab0d83e3632eeeefc

2024-07-19 12:43 UTC, TomckySan commented
修正後動作確認 📝 
https://github.com/TomckySan/sandbox/actions/runs/10008228630/job/27664493166

2024-07-22 10:06 UTC, masutaka reviewed
動作良好でした。もう少しです！

今日が 7/22 (mon) の時に `interval: weekly`, `target_day: sunday` を指定 → 2024/07/28 ✅

今日が 7/22 (mon) の時に `interval: weekly`, `target_day: monday` を指定 → 2024/07/29 ✅
https://github.com/masutaka/sandbox/actions/runs/10038477601/job/27740469009

今日が 7/22 (mon) の時に `interval: weekly`, `target_day: tuesday` を指定 → 2024/07/23 ✅

今日が 7/22 (mon) の時に `interval: daily` を指定 → 2024/07/23 ✅
https://github.com/masutaka/sandbox/actions/runs/10038656706/job/27741046102

2024-07-22 10:07 UTC, masutaka commented
PR description 少し更新しておきました。

> 修正後動作確認 📝
> https://github.com/TomckySan/sandbox/actions/runs/10008228630/job/27664493166

パブリックリポジトリを使ったほうが良いと思います！

2024-07-22 10:32 UTC, TomckySan commented
> レビュアーに見せるためであれば、パブリックリポジトリを使ったほうが良いと思います！

パブリックリポジトリに切り替えました！（一時的にプライベートにしてた。。 😣

2024-07-25 13:51 UTC, TomckySan commented
@masutaka 
変更点、動作影響ないと思いつつ念の為動作確認してました。
問題なかったので改めてレビューお願いします！

2024-07-29 03:00 UTC, masutaka approved these changes
LGTM!

2024-07-29 09:43 UTC, TomckySan commented
ありがとうございました！！！ 🙌🏻

2024-07-29 09:43 UTC, merged

2024-07-30 02:16 UTC, MH4GF commented on .github/workflows/get_next_scheduled_date.yml
> +        description: daily, weeklyのいずれかを指定してください。
dailyも選べるのいいですね 🙌🏻